### ISSUE TITLE
Can I get Bitmap Fonts?

### ISSUE THREAD

**Issue by bipinkrish** [sign-language-processing/signwriting#3]
I want these font files https://github.com/sign-language-processing/signwriting/tree/main/signwriting/visualizer in Bitmap type [FNT].

I tried https://ttf2fnt.com but it seems not working.

**Comment by bipinkrish** [comment]
I need it for its `dart` implementation https://github.com/bipinkrish/signwriting

**Comment by AmitMY** [comment]
Seems like TTF files are supported in Dart https://docs.flutter.dev/cookbook/design/fonts
The SignWriting fonts library is this one - https://github.com/sutton-signwriting/font-ttf
You might be able to re-pack the font from the original glyphs, but I have no idea about that personally.

**Comment by bipinkrish** [comment]
> Seems like TTF files are supported in Dart https://docs.flutter.dev/cookbook/design/fonts

That is for using the font for the UI with flutter SDK, for my need i should be able to load it with dart SDK.

**Comment by bipinkrish** [comment]
> The SignWriting fonts library is this one - https://github.com/sutton-signwriting/font-ttf You might be able to re-pack the font from the original glyphs, but I have no idea about that personally.

I will check it out. Thanks.
